name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4

      # 手动安装 Yarn 依赖，允许修改 lockfile
      - name: Install dependencies
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          yarn install
        
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'iflyelf.com' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env production --minify src/index.js
          environment: production
