name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4

      # 1. 拉取代码
      - uses: actions/checkout@v4

      # 2. 安装 Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3. 安装 Yarn 4
      - run: npm install -g yarn@4

      # 4. 手动安装依赖，允许修改 lockfile
      - name: Install dependencies
        run: |
          export YARN_ENABLE_IMMUTABLE_INSTALLS=false
          yarn install

      # 5. 安装 wrangler CLI
      - run: npm install -g wrangler@3
        
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        env:
          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN || 'iflyelf.com' }}
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CF_ACCOUNT_ID}}
          vars:
            CUSTOM_DOMAIN
          command: deploy --env production --minify src/index.js
          environment: production
